name: Code Formatting

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: "OTQyOTk3NTkzMzU5NzkwMTQx.Ygso8g.pmCG1F0o_9lb7oAbIAK0zbPJi7E"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Check code formatting
        run: ./gradlew spotlessCheck
